# Generated by Django 2.2.3 on 2020-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20, unique=True, verbose_name='食物名称')),
                ('food_alias', models.CharField(max_length=50, verbose_name='食物别名')),
                ('food_type', models.IntegerField(choices=[(0, '未分类'), (1, '主食'), (2, '蛋、肉、奶'), (3, '蔬菜和水果'), (4, '油、调味品'), (5, '饮品')], verbose_name='食物分类')),
                ('food_calories', models.IntegerField(verbose_name='食物热量（大卡）')),
                ('food_purine', models.IntegerField(verbose_name='食物嘌呤含量（mg）')),
                ('food_carbohydrate', models.IntegerField(verbose_name='食物碳水含量（克）')),
                ('food_protein', models.IntegerField(verbose_name='食物蛋白质含量（克）')),
                ('food_fat', models.IntegerField(verbose_name='食物脂肪含量（克）')),
                ('food_cellulose', models.IntegerField(verbose_name='食物纤维素含量（克）')),
                ('food_description', models.CharField(max_length=150, verbose_name='食物描述')),
                ('food_create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('food_is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name_plural': '食物',
            },
        ),
    ]
