# Generated by Django 2.2.3 on 2020-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_carbohydrate',
            field=models.FloatField(verbose_name='食物碳水含量（克）'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_cellulose',
            field=models.FloatField(verbose_name='食物纤维素含量（克）'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_fat',
            field=models.FloatField(verbose_name='食物脂肪含量（克）'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_protein',
            field=models.FloatField(verbose_name='食物蛋白质含量（克）'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_purine',
            field=models.IntegerField(verbose_name='食物嘌呤含量（毫克）'),
        ),
    ]
